name: GraalVM Check

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'Skip GraalVM Check')

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "17"
          distribution: "graalvm-community"
          set-java-home: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check GraalVM installation
        run: |
          echo "GRAALVM_HOME: ${{ env.GRAALVM_HOME }}"
          echo "JAVA_HOME: ${{ env.JAVA_HOME }}"
          native-image --version
          
      - name: Check and Download JAR Files
        run: |
          libs_dir="native/libs"
          sapidoc_jar="${libs_dir}/sapidoc3.jar"
          sapjco_jar="${libs_dir}/sapjco3.jar"

          mkdir -p $libs_dir

          if [ ! -f "$sapidoc_jar" ] || [ ! -f "$sapjco_jar" ]; then
            echo 'JAR files are missing. Downloading...'

            user=${{ secrets.BALLERINA_BOT_USERNAME }}
            token=${{ secrets.BALLERINA_BOT_TOKEN }}
            encoded_auth=$(echo -n "$user:$token" | base64)

            curl -fL -o "$sapidoc_jar" -H "Authorization: Basic $encoded_auth" "https://github.com/wso2-enterprise/wso2-sap-resources/blob/master/resources/lib/sapidoc3.jar?raw=true" || { echo 'Failed to download sapidoc3.jar'; exit 1; }
            curl -fL -o "$sapjco_jar" -H "Authorization: Basic $encoded_auth" "https://github.com/wso2-enterprise/wso2-sap-resources/blob/master/resources/lib/sapjco3.jar?raw=true" || { echo 'Failed to download sapjco3.jar'; exit 1; }
          else
            echo 'JAR files already exist in native/libs/ directory.'
          fi

      - name: Set ENV Variables
        run: |
          echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV

      - name: Clone lib repo
        uses: actions/checkout@v3
        with:
          repository: wso2-enterprise/wso2-sap-resources
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          path: 'wso2-sap-resources'

      - name: Copy Libs to SAP Connector Directory
        run: |
          cd $GITHUB_WORKSPACE
          cp -r wso2-sap-resources/ballerina_resources/lib/. native/libs/

      - name: Build Package
        run: ./gradlew build
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove Target Directory
        run: sudo rm -rf ballerina/target

      - name: Test with GraalVM
        run: |
          cd ballerina
          bal test --graalvm
