name: Build

on:
  push:
    branches:
      - main
      - 2201.[0-9]+.x
  repository_dispatch:
    types: check_connector_for_breaking_changes

jobs:
  ubuntu-build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-ubuntu-build
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: jco

      - name: Get Ballerina Version
        run: |
          cd jco
          BAL_VERSION=$(grep -w 'ballerinaLangVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev) 
          if [ -z "$BAL_VERSION" ]; then
            BAL_VERSION="latest"
          fi
          echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
          echo "Ballerina Version: $BAL_VERSION"

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: ${{ env.BAL_VERSION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17.0.7

      - name: Clone lib repo
        uses: actions/checkout@v4
        with:
          repository: wso2-enterprise/wso2-sap-resources
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          path: libs

      - name: Copy Libs to SAP Connector Directory
        run: |
          cp -r libs/ballerina_resources/lib/. jco/native/libs/

      - name: Build the Package
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd jco
          ./gradlew build -x test

      - name: Generate Codecov Report
        uses: codecov/codecov-action@v3
