name: PR Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on: pull_request

jobs:
  ubuntu-build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-ubuntu-build
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: jco
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.7
                
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Clone lib repo
        uses: actions/checkout@v4
        with:
          repository: wso2-enterprise/wso2-sap-resources
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          path: libs

      - name: Copy Libs to SAP Connector Directory
        run: |
          cp -r libs/ballerina_resources/lib/. jco/native/libs/

      - name: Build the Package
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -x test
        working-directory: jco

      - name: Generate Codecov Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
