name: Publish Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [stdlib-release-pipeline]

jobs:
  publish-release:
    name: Release Package
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Ballerina Version
        run: |
          BAL_VERSION=$(grep -w 'ballerinaLangVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev) 
          if [ -z "$BAL_VERSION" ]; then
            BAL_VERSION="latest"
          fi
          echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
          echo "Ballerina Version: $BAL_VERSION"

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: ${{ env.BAL_VERSION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17.0.7

      - name: Check and Download JAR Files
        run: |
          libs_dir="native/libs"
          sapidoc_jar="${libs_dir}/sapidoc3.jar"
          sapjco_jar="${libs_dir}/sapjco3.jar"

          mkdir -p $libs_dir

          if [ ! -f "$sapidoc_jar" ] || [ ! -f "$sapjco_jar" ]; then
            echo 'JAR files are missing. Downloading...'

            user=${{ secrets.BALLERINA_BOT_USERNAME }}
            token=${{ secrets.BALLERINA_BOT_TOKEN }}
            encoded_auth=$(echo -n "$user:$token" | base64)

            curl -fL -o "$sapidoc_jar" -H "Authorization: Basic $encoded_auth" "https://github.com/wso2-enterprise/wso2-sap-resources/blob/master/resources/lib/sapidoc3.jar?raw=true" || { echo 'Failed to download sapidoc3.jar'; exit 1; }
            curl -fL -o "$sapjco_jar" -H "Authorization: Basic $encoded_auth" "https://github.com/wso2-enterprise/wso2-sap-resources/blob/master/resources/lib/sapjco3.jar?raw=true" || { echo 'Failed to download sapjco3.jar'; exit 1; }
          else
            echo 'JAR files already exist in native/libs/ directory.'
          fi

      - name: Set ENV Variables
        run: |
          echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV

      - name: Build without Tests
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name ${{ secrets.BALLERINA_BOT_USERNAME }}
          git config --global user.email ${{ secrets.BALLERINA_BOT_EMAIL }}
          ./gradlew build -x test

      - name: Create lib Directory if not Exists
        run: mkdir -p ballerina/lib

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "rootfs"
          scan-ref: "/github/workspace/ballerina/lib"
          format: "table"
          timeout: "10m0s"
          exit-code: "1"
          skip-dirs: "examples"

      - name: Get Release Version
        run: echo "VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut -d- -f2 | rev)" >> $GITHUB_ENV

      - name: Checkout to Release Branch
        run: |
          echo "Version: ${VERSION}"
          git checkout -b release-${VERSION}

      - name: Remove Target Directory
        run: |
          sudo rm -rf ballerina/target
          sudo rm -rf ballerina/build

      - name: Publish Package
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          publishUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          publishPAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ./gradlew clean release -Prelease.useAutomaticVersion=true
          ./gradlew -Pversion=${VERSION} publish -x test -PpublishToCentral=true

      - name: GitHub Release and Release Sync PR
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          gh release create v$VERSION --title "module-ballerinax-sap.jco-v$VERSION"
          gh pr create --base ${GITHUB_REF##*/} --title "[Automated] Sync ${GITHUB_REF##*/} after $VERSION release" --body "Sync ${GITHUB_REF##*/} after $VERSION release"
