[package]
org = "wso2"
name = "sap_inventory_update"
version = "0.1.0"
distribution = "2201.9.1"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
path = "../../native/libs/sapidoc3.jar"
groupId="com.sap"
artifactId="com.sap.conn.idoc"
version="3.1.3"

[[platform.java17.dependency]]
path = "../../native/libs/sapjco3.jar"
groupId="com.sap"
artifactId="com.sap.conn.jco"
version="3.1.9"
